# Site settings
title: Ayman Fatich 
description: >-
  My Personal website where you can find my resume, blog posts, and projects.
  Welcome to my corner of the internet!
lang: en-US 
timezone: Europe/Paris 
image: 
repo: 
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Ayman Fatich # author name
  bio: >- # tell to the world
    Engineer, I love making stuff, writing stuff, and hacking stuff. Welcome to my corner of the internet!
  username: ayman-fatich # general username
  github: ayman-fatich # github username
  linkedin: fatich # linkedin username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: fatich@eurecom.fr # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://ayman-fatich.github.io" #
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
